"""add employee_meetings association table

Revision ID: 9126d9244a47
Revises: 568ade36de7d
Create Date: 2025-03-29 13:04:33.475781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9126d9244a47'
down_revision = '568ade36de7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_meetings',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('meetings_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_employee_meetings_employee_id_employees')),
    sa.ForeignKeyConstraint(['meetings_id'], ['meetings.id'], name=op.f('fk_employee_meetings_meetings_id_meetings')),
    sa.PrimaryKeyConstraint('employee_id', 'meetings_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee_meetings')
    # ### end Alembic commands ###
